# Generated by Django 2.2.7 on 2019-11-17 15:06

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191117_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=social.models.get_file_path),
        ),
    ]
