# Generated by Django 2.2.7 on 2019-11-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191119_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='profile',
            new_name='userprofile',
        ),
    ]
