# Generated by Django 2.2.7 on 2019-11-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191120_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='userprofile',
            new_name='author',
        ),
    ]
