# Generated by Django 2.2.7 on 2019-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='users.Profile'),
        ),
    ]
